#!/usr/bin/env bash

HOME_DIR="$HOME"
CACHE_FILE="$HOME_DIR/.cache_aiflow_dags_test.txt"

# Время кэша в секундах
NOW=$(date +%s)

# Создаем кэш файл если его нет
if ! test -f $CACHE_FILE; then
        touch "$CACHE_FILE"
fi

# COMMAND="airflow"
COMMAND="docker compose exec -it airflow-worker airflow"
TEST_COMMAND="$COMMAND dags test"


# Проверяем существование и размер кэш-файла
if [ -f "$CACHE_FILE" ] && [ -s "$CACHE_FILE" ]; then
        # Получаем время создания файла
        FILETIME=$(stat -f %m "$CACHE_FILE")

        # Считаем разницу между текущим временем и временем создания файла
        DIFF=$((NOW - FILETIME))

        # Если разница меньше 5 минут, используем закэшированные результаты
        if [ "${DIFF}" -lt "1800" ]; then
                selected_dag=`cat $CACHE_FILE | fzf`
                if [[ $selected_dag == *"_last command:"* ]]; then
                        # Разбиваем строку по :
                        IFS=":" read -r prefix command <<< "$selected_dag"
                        command=${command# }
                        command=${command% }
                        echo "Запускаю команду: $command"
                        eval "$command"
                        exit
                fi

        else
                list_dags=`$COMMAND dags list | awk '{print $1}' | grep -oE "^[a-zA-Z0-9_]+$"`
                selected_dag=`echo "$list_dags" | fzf`
                echo "$list_dags" > $CACHE_FILE
        fi
else
        list_dags=`$COMMAND dags list | awk '{print $1}' | grep -oE "^[a-zA-Z0-9_]+$"`
        selected_dag=`echo "$list_dags" | fzf`
        echo "$list_dags" > $CACHE_FILE
fi



if [[ -z $selected_dag ]]; then
    echo "Ой все!"
    exit 0
fi

echo "Запускаю команду: $TEST_COMMAND $selected_dag"
$TEST_COMMAND $selected_dag
