-- vim.g.gitblame_display_virtual_text = 1 -- Disable virtual text
-- vim.g.gitblame_delay = 1000
-- vim.g.gitblame_message_template = "<summary> • <date> • <author>"
-- vim.g.gitblame_message_when_not_committed = "Oh please, commit this !"
-- vim.g.gitblame_date_format = "%r"
-- vim.g.gitblame_highlight_group = "Question"
-- vim.g.gitblame_display_virtual_text = 0
-- local git_blame = require("gitblame")

-- require("hardline").setup({
--     sections = {
--         lualine_c = {
--             { git_blame.get_current_blame_text, cond = git_blame.is_blame_text_available },
--         },
--     },
-- })
